@url=http://localhost:8100
@json=Content-Type: application/json

### find_ip_address
POST {{url}}/find_ip_address
{{json}}

[{}]

### update_ip_address
POST {{url}}/update_ip_address
{{json}}

{
    "_id": "645fbcaa2ad769d5c0b5ee3b",
    "remark": "this is test remark"
}

